apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: github-webapp
  name: github-webapp-deployment
  namespace: github-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-webapp
  template:
    metadata:
      labels:
        app: github-webapp
    spec:
      containers:
      - image: ghcr.io/cmarquetand/webapp:1.0.27
        name: github-webapp
        #imagePullPolicy: Always
        #ports:
        #- containerPort: 5000
        #  name: http
